AWSTemplateFormatVersion: "2010-09-09"
Description: "CSR Lambda API System - 超シンプル開発環境"

Parameters:
  ProjectName:
    Type: String
    Default: csr-lambda-api
    Description: プロジェクト名

  Environment:
    Type: String
    Default: dev
    Description: 環境名

Resources:
  # フロントエンド用S3バケット（最小構成）
  FrontendS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-${Environment}-frontend"
        - Key: Environment
          Value: !Ref Environment

Outputs:
  FrontendS3BucketName:
    Description: フロントエンド用S3バケット名
    Value: !Ref FrontendS3Bucket
    Export:
      Name: !Sub "${ProjectName}-${Environment}-frontend-bucket-name"

  FrontendS3BucketWebsiteURL:
    Description: フロントエンド用S3バケットWebサイトURL
    Value: !GetAtt FrontendS3Bucket.WebsiteURL
    Export:
      Name: !Sub "${ProjectName}-${Environment}-frontend-website-url"
